# Project: Online Payment Fraud Detection
## Data Cleaning

### Import Libraries

In [1]:
# Libraries
import numpy as nun
import pandas as pd

## Load Dataset

In [2]:
# Dataset
df = pd.read_csv(r"D:\Portfolio\Online_Payment_Fraud_Detection\data\transactions_test.csv")
df.head()

,transaction_id,transaction_time,customer_id,merchant_id,account_age_days,credit_score_band,kyc_level,avg_monthly_spend,merchant_risk_score,transaction_amount,...,device_type,is_international,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,is_fraud,post_auth_risk_score
0,305461,2023-10-01 00:02:41.559131982,11453,7397,1417,4,2,7549.746993,0.056340,1783.564199,...,mobile,0,0.417366,1,2,0,54.226534,1531.905966,0,0.358507
1,341279,2023-10-01 00:06:25.507380194,28021,97,830,2,2,2766.322082,0.736960,7038.755549,...,mobile,0,0.272247,1,3,1,60.728405,6946.544813,0,0.065886
2,344364,2023-10-01 00:07:50.846454903,2269,2796,1651,2,3,3988.151593,0.454618,663.057016,...,mobile,0,0.446442,3,3,0,102.171038,530.118629,0,0.026225
3,84227,2023-10-01 00:17:11.834872052,32373,787,1207,1,2,5472.122178,0.417973,1665.509484,...,desktop,0,0.308703,2,3,0,10.146806,1483.105412,0,0.201940
4,187825,2023-10-01 00:19:50.841780964,13548,4439,1926,5,2,1758.784635,0.535169,1524.306346,...,mobile,1,0.305401,2,1,1,18.328551,1465.680191,0,0.234395

## Data Backup

In [3]:
# Back-up of the dataset
cleaned_data = df.copy()
cleaned_data.head()

,transaction_id,transaction_time,customer_id,merchant_id,account_age_days,credit_score_band,kyc_level,avg_monthly_spend,merchant_risk_score,transaction_amount,...,device_type,is_international,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,is_fraud,post_auth_risk_score
0,305461,2023-10-01 00:02:41.559131982,11453,7397,1417,4,2,7549.746993,0.056340,1783.564199,...,mobile,0,0.417366,1,2,0,54.226534,1531.905966,0,0.358507
1,341279,2023-10-01 00:06:25.507380194,28021,97,830,2,2,2766.322082,0.736960,7038.755549,...,mobile,0,0.272247,1,3,1,60.728405,6946.544813,0,0.065886
2,344364,2023-10-01 00:07:50.846454903,2269,2796,1651,2,3,3988.151593,0.454618,663.057016,...,mobile,0,0.446442,3,3,0,102.171038,530.118629,0,0.026225
3,84227,2023-10-01 00:17:11.834872052,32373,787,1207,1,2,5472.122178,0.417973,1665.509484,...,desktop,0,0.308703,2,3,0,10.146806,1483.105412,0,0.201940
4,187825,2023-10-01 00:19:50.841780964,13548,4439,1926,5,2,1758.784635,0.535169,1524.306346,...,mobile,1,0.305401,2,1,1,18.328551,1465.680191,0,0.234395

In [4]:
# Information about the dataset
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99887 entries, 0 to 99886
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   transaction_id                   99887 non-null  int64
 1   transaction_time                 99887 non-null  object
 2   customer_id                      99887 non-null  int64
 3   merchant_id                      99887 non-null  int64
 4   account_age_days                 99887 non-null  int64
 5   credit_score_band                99887 non-null  int64
 6   kyc_level                        99887 non-null  int64
 7   avg_monthly_spend                99887 non-null  float64
 8   merchant_risk_score              99887 non-null  float64
 9   transaction_amount               99887 non-null  float64
 10  payment_channel                  99887 non-null  object
 11  device_type                      99887 non-null  object
 12  is_international                 99887 non-null  int64
 13  ip_risk_score                    99887 non-null  float64
 14  txn_count_1h                     99887 non-null  int64
 15  txn_count_24h                    99887 non-null  int64
 16  failed_txn_count_24h             99887 non-null  int64
 17  geo_distance_from_last_txn       99887 non-null  float64
 18  amount_deviation_from_user_mean  99887 non-null  float64
 19  is_fraud                         99887 non-null  int64
 20  post_auth_risk_score             99887 non-null  float64
dtypes: float64(7), int64(11), object(3)
memory usage: 16.0+ MB

In [5]:
# Remove irrelevent columns
cleaned_data = cleaned_data.drop(columns=["customer_id",
            "merchant_id",
            "transaction_time"], errors = "ignore")

print(cleaned_data.columns.tolist())
print(cleaned_data.shape)

['transaction_id', 'account_age_days', 'credit_score_band', 'kyc_level', 'avg_monthly_spend', 'merchant_risk_score', 'transaction_amount', 'payment_channel', 'device_type', 'is_international', 'ip_risk_score', 'txn_count_1h', 'txn_count_24h', 'failed_txn_count_24h', 'geo_distance_from_last_txn', 'amount_deviation_from_user_mean', 'is_fraud', 'post_auth_risk_score']
(99887, 18)

In [6]:
# Check the null values of the dataset
cleaned_data.isnull().sum()

transaction_id                     0
account_age_days                   0
credit_score_band                  0
kyc_level                          0
avg_monthly_spend                  0
merchant_risk_score                0
transaction_amount                 0
payment_channel                    0
device_type                        0
is_international                   0
ip_risk_score                      0
txn_count_1h                       0
txn_count_24h                      0
failed_txn_count_24h               0
geo_distance_from_last_txn         0
amount_deviation_from_user_mean    0
is_fraud                           0
post_auth_risk_score               0
dtype: int64

In [7]:
# Shows all rows that are duplicated
print("Duplicate Values \n", cleaned_data.duplicated().sum())

Duplicate Values
 0

In [8]:
#-----------Step 1: Check ---------------------
before = cleaned_data.shape[0]
duplicates = cleaned_data.duplicated().sum()
print(f"Duplicate rows found: {duplicates}")

#----------Step 2: Remove ---------------------
cleaned_data = cleaned_data.drop_duplicates()

#----------Step 3: Confirm --------------------
after = cleaned_data.shape[0]
print(f"Rows before : {before:,}")
print(f"Rows after : {after:,}")
print(f"Rows removed: {before - after:,}")

Duplicate rows found: 0
Rows before : 99,887
Rows after : 99,887
Rows removed: 0

## Export Cleaned Dataset

In [ ]:
#---- Export Cleaned dataset -----------------------------------
cleaned_data.to_csv(r"D:\Portfolio\Online_Payment_Fraud_Detection\data\cleaned_data.csv", index = False)